update ci cd

diff --git a/.github/workflows/ci-cd.yml b/.github/workflows/ci-cd.yml
--- a/.github/workflows/ci-cd.yml
+++ b/.github/workflows/ci-cd.yml
@@ -47,6 +47,18 @@ jobs:
           cd sources/batch_processing/airflow/dag-airflow
           docker compose --env-file .env up -d
 
+      - name: Verify Airflow DAGs
+        run: |
+          echo "Checking if DAG 'data_ingestion_aws_project' exists..."
+          dag_list=$(docker exec -i dtc-de-airflow-webserver-1 airflow dags list | grep 'data_ingestion_aws_project' || true)
+          if [ -z "$dag_list" ]; then
+            echo "Error: DAG 'data_ingestion_aws_project' not found."
+            exit 1
+          else
+            echo "DAG 'data_ingestion_aws_project' is available."
+          fi
+      
+
       - name: Trigger Airflow DAG
         run: |
           echo "Triggering Airflow DAG..."
